/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        4: "4px",
        8: "8px",
        16: "16px",
        24: "24px",
        32: "32px",
        64: "64px",
      },
      padding: {
        8: "8px",
        16: "16px",
        24: "24px",
        32: "32px",
      },
      fontSize: {
        "display-1": "64px",
        "display-2": "56px",
        h1: "44px",
        h2: "40px",
        h3: "32px",
        h4: "24px",
        h5: "20px",
        h6: "16px",
        h7: "20px",
        "body-xl": "20px",
        "body-lg": "18px",
        "body-md": "16px",
        "body-sm": "14px",
        "caption-lg": "14px",
        "caption-md": "12px",
        "caption-sm": "10px",
        "button-lg": "16px",
        "button-sm": "14px",
        "overline-lg": "16px",
        "overline-sm": "12px",
      },
      lineHeight: {
        120: "120%",
        140: "140%",
        180: "180%",
        24: "24px",
      },
    },
  },
  plugins: [],
};
